### PR TITLE
Firefox: Port from chrome theme

### PR DESCRIPTION
**Pull request by tong**
screenshot-adapta-firefox
screenshot-adapta_nokto-firefox

### CODE REVIEW

**Comment by ArchangeGabriel** [comment]
This is Persona theming right?

**Comment by tong** [comment]
Persona?

https://developer.mozilla.org/en-US/Add-ons/Themes

**Comment by ArchangeGabriel** [comment]
Old name of Lightweight themes apparently. ;

> Personas (now known as lightweight themes).

(From Personas Plus add-on page)

So yes. I was just checking since this is the only theming support remaining in Firefox AFAIK (full theming was removed bit by bit).

**Comment by tista500** [comment]
Won't merge, sorry.

**Pull request closed without merging**
